name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/docs/**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Configure corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm i

      - name: Check lint
        run: pnpm run lint:js

      - name: Check Tests
        run: pnpm run test

      - name: Build lib
        run: pnpm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run generate:release
